name: untitled2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:

    sdk: flutter
  flutter_localizations:
    sdk: flutter  # This enables localization support
  cupertino_icons: ^1.0.6
  provider: ^6.0.0
  shared_preferences: ^2.0.6
  http: ^0.13.0  # Ensure version compatibility as previously discussed
  url_launcher: ^6.0.20
  image_picker: ^0.8.5+3
  google_fonts: ^2.0.0
  tflite: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Asset configuration if you have images or other files
  assets:
    - assets/       # Adjust to match any assets used in your main.dart

  # Fonts can be configured here if custom fonts are used
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
